# Generated by Django 2.0.7 on 2018-07-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zanbil', '0002_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='image',
            field=models.ImageField(default='2.jpg', upload_to=''),
        ),
    ]
