# Generated by Django 2.0.7 on 2018-07-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zanbil', '0003_business_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='cancelation_time',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='services',
            name='cancellation_fee',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='services',
            name='off',
            field=models.FloatField(default=0),
        ),
    ]
