# Generated by Django 2.0.7 on 2018-07-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zanbil', '0004_auto_20180705_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='firstSans',
            field=models.FloatField(default=8),
        ),
        migrations.AddField(
            model_name='services',
            name='lastSans',
            field=models.FloatField(default=20),
        ),
        migrations.AlterField(
            model_name='services',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
